services:
  # Spring Boot Backend
  backend:
    build: .
    container_name: oncolly-backend
    ports:
      - "8888:8888"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/oncolly
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      database:
        condition: service_healthy

  # Postgres Database
  database:
    image: postgres:15-alpine
    container_name: oncolly-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: oncolly
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data: